Isso mano, sugiro seguir o seguinte cronograma:

1 = Estude Linux, entenda como funciona o sistema em si o livro que lhe apresentei dará um bom rederecionamento para ti. E não se acanhe viaje no mundo linux, tem diversos livro legais pegue meu conteúdo principal https://mega.nz/#F!kVUzWJhK!cs1_ee23bfNeQVfWLwEJhw

2= Estude redes, poderá pegar o livro sobre Rede e Servidores linux no link acima. Porém se quer algo bem profundo vá atrás do livro Redes de Computadores Tanebaum excelente, ele é super avançado sugiro que estude ele todo só se quiser se tornar um administrador em redes de computadores

3= Segurança, logo após esssa longa jornada ai sim poderá ir para segurança toma um link muito bom dos meus matériais: https://mega.nz/#F!hdMykAiT!6SBQwivXCDWOY4EZDBL5WQ
